<?php

namespace Music\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * AlbumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumsRepository extends EntityRepository
{
    public  function search($word)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.group_name LIKE :word')
            ->orWhere('a.track_name LIKE :word')
            ->orWhere('a.file_name LIKE :word')
            ->setParameter('word', '%'.$word.'%')
            ->orderBy('a.id','DESC')
            ->getQuery()
            ->getResult();
//        if(empty($qb)){
//            $qb = $this->findAll('DESC');
//            return $qb;
//        }
        return $qb;

    }

//    public function findAll($order = 'ASC')
//    {
//        return $this->findBy(array(), array('id'=>$order));
//    }


}
